### PR TITLE
Proposing several updates, for first half of page

### PR DESCRIPTION
**Pull request by carehart**
I was torn whether to do them as one commit or spread out. In case you may have had a concern with any, I erred on the side of an individual commit per change. I hope to get time to assess the second half of the list of items.

### CODE REVIEW

**Comment by seancoyne** [comment]
Thanks Charlie!

**Comment by carehart** [comment]
Thanks, Sean. And if I do more, do you like them in separate commits, or perhaps all as one. Whatever you prefer is fine by me.

**Comment by seancoyne** [comment]
You can do them all at once.  I trust your changes will be spot on.

**Comment by carehart** [comment]
Ok, thanks. :-). And for all your efforts here.

**Pull request merged**
